functional:
 - Авторизация через сторонние сайты
 - Возможность выбора языка программирования
 - Возможность игры с другими играками, а также в режиме " сам с собой"|
   т.е с компьютером и турниров
 - Введение рейтинга игроков за определенный период
 - Возможность обмениваться сообщениями между игроками голос/печать
 - Уведомления о начале игры или же от других игроков (всеми доступными способами)
 - Проводить игру в режиме онлайн с возможностью присутствия зрителей
 - Выбор уровня сложности
 - Наличие таймера и возможность задавать временной промежуток перед началом игры
 - Обозначение победителя в виде отличительного знака над аватаркой.
 - После окончания игры есть возможность 
 - Автоматическое переподключение игрока к серверу в случае разрава связи
 non-functional:
  - Разработка с учетом удобства использования и оптимизировать для скорости работы
  - Безопасным и защищать данные пользователя
  - Иметь мобильную версию
  - Протестировать на совместимость с последними версиями браузеров
  - Должен быть доступен на различных устройствах
  - Иметь локализацию (перевод) на русский и английский языки
  - Важно,  обрабатывать большое количество трафика
  - Хранине данных пользователя(рейтинг, аутификация и т.д)
  implicit:
  - Не активное окно соседнего игрока, т.е ввести (код) в окно противника-не возможно
  - Для зрителей окна ввода непосредственных игроков- не активны
  - Простота использования
  - Информация на сайте должна быть "легкой"
  - Возможность вести игру с ботом
  - Шифрование данных
  - Разработка моб. версии
  - Корректная работа сайта во всех блаузерах и устройствах
  - Мультиязычный сайт
  - Возможность коментирования игры зритилями в режиме реального времени.
  - Общение между участниками соревнований голосом во время командного турнира.

